version: "3.8"
services:
  mongodb:
    image: "mongo:5.0"
    volumes:
      - "mongodb_dataa:/data/db"
    restart: "on-failure"

  opensearch:
    image: "opensearchproject/opensearch:2.4.0"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx4g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
        #      - "indices.queries.cache.size=500"
      - "indices.fielddata.cache.size=1gb"
      - "thread_pool.write.queue_size=1000"
      - "indices.memory.index_buffer_size=512mb"
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms2048m -Xmx2048m"
      - 'http.host=0.0.0.0'
      - 'transport.host=localhost'
      - 'network.host=0.0.0.0'
      - "indices.mapper.dynamic: false"
      - "index.mapping.ignore_malformed: true"
        #      - "index.mapping.ignore_above: 32000"
    ports:
      - '9200:9200'
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - "os_dataa:/usr/share/opensearch/data"
    restart: "on-failure"
  graylog:
    hostname: "server"
    image: graylog/graylog:5.0.6
    depends_on:
      opensearch:
        condition: "service_started"
      mongodb:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_PASSWORD_SECRET: "53sZX2TNnkB9D2Gp7gq46q2k2v8YBXch"
      GRAYLOG_ROOT_PASSWORD_SHA2: "d84033ee8485e2e85fd6219cc9be8083c10e92efbe40a56699fbd0cb846829fe"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      GRAYLOG_SERVER_JAVA_OPTS: "-Xms6g -Xmx6g"
    ports:
    - "5044:5044/tcp"   # Beats
    - "5140:5140/udp"   # Syslog
    - "5140:5140/tcp"   # Syslog
    - "5555:5555/tcp"   # RAW TCP
    - "5555:5555/udp"   # RAW TCP
    - "9000:9000/tcp"   # Server API
    - "12201:12201/tcp" # GELF TCP
    - "12201:12201/udp" # GELF UDP
    #- "10000:10000/tcp" # Custom TCP port
    #- "10000:10000/udp" # Custom UDP port
    - "13301:13301/tcp" # Forwarder data
    - "13302:13302/tcp" # Forwarder config
    volumes:
      - "graylog_dataa:/usr/share/graylog/data/data"
      - "graylog_journall:/usr/share/graylog/data/journal"
    restart: "on-failure"

volumes:
  mongodb_dataa:
  os_dataa:
  graylog_dataa:
  graylog_journall:
